import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import App from "../Components/App";

const StaticHome: NextPage = (props) => {
  const [data, setData] = useState("");
  useEffect(() => {
    fetch("https://random-data-api.com/api/address/random_address").then(
      (response) => response.json().then((data) => setData(data))
    );
  }, []);

  return (
    <div
      style={{
        width: "100vw",
      }}
    >
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App
        props={{
          mockAddress: data,
        }}
      />
    </div>
  );
};

export default StaticHome;
